// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVOZZJEImEownPFtIDvZPeZp2R4muM9w',
    appId: '1:230831538559:android:581a18769c36354f109a4a',
    messagingSenderId: '230831538559',
    projectId: 'extreme-quasar-494406-v7',
    storageBucket: 'extreme-quasar-494406-v7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCeNFpKr-R2dQWElYhzrMoDN_qAYG_Jc',
    appId: '1:230831538559:ios:f18de25cc9135fb1109a4a',
    messagingSenderId: '230831538559',
    projectId: 'extreme-quasar-494406-v7',
    storageBucket: 'extreme-quasar-494406-v7.firebasestorage.app',
    iosClientId: '230831538559-8adaulnc7rd66dlug5gu55esgk0gse26.apps.googleusercontent.com',
    iosBundleId: 'tw.yujiantailuge.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6SlI2ttzzS9z5RO5Mt-XyMWY_3cItKpI',
    appId: '1:230831538559:web:128976472264c677109a4a',
    messagingSenderId: '230831538559',
    projectId: 'extreme-quasar-494406-v7',
    authDomain: 'extreme-quasar-494406-v7.firebaseapp.com',
    storageBucket: 'extreme-quasar-494406-v7.firebasestorage.app',
    measurementId: 'G-X3PRSE1T6J',
  );
}
